// mock.ts - STUB FILE (Phase 2 switched to real backend)
// This file replaces the corrupted GBK mock data with empty stubs.
// All functions return empty/placeholder values; real data comes from backend API.
// Phase 2: VITE_APP_MOCK_ENABLED=false in .env means these are never called at runtime.

export const mockLogin = (..._args: any[]): any => ({})
export const mockGetUserList = (..._args: any[]): any => ({})
export const mockGetRoleList = (..._args: any[]): any => ({})
export const mockCreateRole = (..._args: any[]): any => ({})
export const mockUpdateRole = (..._args: any[]): any => ({})
export const mockDeleteRole = (..._args: any[]): any => ({})
export const mockGetHeroCards = (..._args: any[]): any => ({})
export const mockGetContentCards = (..._args: any[]): any => ({})
export const mockGetRoomList = (..._args: any[]): any => ({})
export const mockGetAllRooms = (..._args: any[]): any => ({})
export const mockCreateRoom = (..._args: any[]): any => ({})
export const mockUpdateRoom = (..._args: any[]): any => ({})
export const mockDeleteRoom = (..._args: any[]): any => ({})
export const mockGetOrderList = (..._args: any[]): any => ({})
export const mockGetAllOrders = (..._args: any[]): any => ({})
export const mockCreateOrder = (..._args: any[]): any => ({})
export const mockUpdateOrder = (..._args: any[]): any => ({})
export const mockDeleteOrder = (..._args: any[]): any => ({})
export const mockCheckIn = (..._args: any[]): any => ({})
export const mockCheckOut = (..._args: any[]): any => ({})
export const mockGetCustomerList = (..._args: any[]): any => ({})
export const mockGetAllCustomers = (..._args: any[]): any => ({})
export const mockCreateCustomer = (..._args: any[]): any => ({})
export const mockUpdateCustomer = (..._args: any[]): any => ({})
export const mockDeleteCustomer = (..._args: any[]): any => ({})
export const mockGetDashboardStats = (..._args: any[]): any => ({})
export const mockCancelBooking = (..._args: any[]): any => ({})
export const mockGetChannelConfigs = (..._args: any[]): any => ({})
export const mockGetChannelConfig = (..._args: any[]): any => ({})
export const mockUpdateChannelConfig = (..._args: any[]): any => ({})
export const mockConnectChannel = (..._args: any[]): any => ({})
export const mockGetChannelSyncLogs = (..._args: any[]): any => ({})
export const mockAppendSyncLog = (..._args: any[]): any => ({})
export const mockGetGuestSpendHistory = (..._args: any[]): any => ({})
export const mockToggleBlacklist = (..._args: any[]): any => ({})
export const mockGetProperties = (..._args: any[]): any => ({})
export const mockGetProperty = (..._args: any[]): any => ({})
export const mockGetRoomTypes = (..._args: any[]): any => ({})
export const mockGetRooms = (..._args: any[]): any => ({})
export const mockUpdateRoomStatus = (..._args: any[]): any => ({})
export const mockGetRatePlans = (..._args: any[]): any => ({})
export const mockGetRateCalendar = (..._args: any[]): any => ({})
export const mockGetInventoryCalendar = (..._args: any[]): any => ({})
